# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ie0Jz9lfe1K2LVwpsaGbYYrjv_Fu7SxI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#B1:Đọc dữ liệu
df = pd.read_csv('/content/GOOGL_stock.csv', skiprows=3, names=['Date', 'Close', 'High', 'Low', 'Open', 'Volume'])
#Xem dữ liệu
df.info()
# BƯỚC 2: TIỀN XỬ LÝ
# 2.1. Chuyển cột Date sang định dạng thời gian
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# 2.2. Ép các cột giá trị về dạng số (đề phòng có chữ lẫn vào)
cols_to_numeric = ['Close', 'High', 'Low', 'Open', 'Volume']
for col in cols_to_numeric:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# 2.3. Xử lý giá trị thiếu (Missing values) và trùng lặp (Duplicates)
print("\nKiểm tra dữ liệu thiếu:")#Nhom kiểm tra dữ liệu thiếu
missing_values = df.isnull().sum()
print(missing_values)

#Kiểm tra dòng bị thiếu
df[df.isnull().any(axis=1)]
#Kiểm tra dòng bị trùng
print(df.duplicated().sum())

df = df.dropna() # Xóa dòng có ô trống
df = df.drop_duplicates() # Xóa dòng trùng

# 2.4. Sắp xếp lại theo đúng trình tự thời gian (Quan trọng cho Time Series)
df = df.sort_values('Date').reset_index(drop=True)
#2.5 Kiểm tra Outlier (Ngoại lệ) bằng Boxplot
plt.figure(figsize=(8, 5))
sns.boxplot(x=df['Close'], color='skyblue')
plt.title("Boxplot of Closing Price (GOOGL) - Kiểm tra Outliers")
plt.xlabel("Giá đóng cửa (Close)")
plt.show()

# BƯỚC 3: CHIA TRAIN/TEST
split_index = int(len(df) * 0.8)
train = df.iloc[:split_index]
test = df.iloc[split_index:]