# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uEpGsva6cReQddN65ZmIu4tOmKcroJND
"""



display(df_clean.head())

"""## Bắt đầu huấn luyện mô hình LSTM"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# Data preprocessing has been skipped as requested.
# Assuming variables like `ts`, `ts_scaled`, `X`, `y`, `X_train`, `X_test`, `y_train`, `y_test`, `scaler`, `df_clean`, `seq_length` are already defined from previous steps.

# --- BƯỚC 3: XÂY DỰNG VÀ TRAINING MÔ HÌNH ---
print("Đang bắt đầu Training... Linh đợi xíu nhé!")

lstm_model = Sequential()
lstm_model.add(LSTM(units=50, return_sequences=True, input_shape=(seq_length, 1)))
lstm_model.add(Dropout(0.2))
lstm_model.add(LSTM(units=50, return_sequences=False))
lstm_model.add(Dropout(0.2))
lstm_model.add(Dense(units=1))

lstm_model.compile(optimizer='adam', loss='mean_squared_error')

# Bắt đầu chạy 20 vòng lặp (Epochs)
history = lstm_model.fit(X_train, y_train, epochs=20, batch_size=32, verbose=1)

# --- BƯỚC 4: DỰ BÁO TRÊN TẬP TEST VÀ VẼ BIỂU ĐỒ ---
lstm_predictions = lstm_model.predict(X_test)
lstm_predictions = scaler.inverse_transform(lstm_predictions)
y_test_inv = scaler.inverse_transform(y_test)

test_dates = ts.index[train_size + seq_length : train_size + seq_length + len(lstm_predictions)]

plt.figure(figsize=(12, 6))
plt.plot(ts.index[:train_size + seq_length], ts.values[:train_size + seq_length], label='Huấn luyện')
plt.plot(test_dates, y_test_inv, label='Thực tế')
plt.plot(test_dates, lstm_predictions, label='Dự báo LSTM', color='green')
plt.title('Dự báo giá đóng cửa GOOG với LSTM')
plt.xlabel('Ngày')
plt.ylabel('Giá đóng cửa')
plt.legend()
plt.show()

# --- BƯỚC 5: ĐÁNH GIÁ SAI SỐ ---
rmse_lstm = np.sqrt(mean_squared_error(y_test_inv, lstm_predictions))
mae_lstm = mean_absolute_error(y_test_inv, lstm_predictions)
mape_lstm = np.mean(np.abs((y_test_inv - lstm_predictions) / y_test_inv)) * 100

print("\n--- KẾT QUẢ ĐÁNH GIÁ TRÊN TẬP TEST ---")
print(f'RMSE: {rmse_lstm:.2f}')
print(f'MAE: {mae_lstm:.2f}')
print(f'MAPE: {mape_lstm:.2f}%')

# --- BƯỚC 6: DỰ BÁO 30 NGÀY TƯƠNG LAI CÓ NGÀY THÁNG ---

# 1. Dự báo 30 bước
last_60_days = ts_scaled[-seq_length:]
current_batch = last_60_days.reshape((1, seq_length, 1))
future_predictions = []

for i in range(30):
    current_pred = lstm_model.predict(current_batch, verbose=0)[0]
    future_predictions.append(current_pred)
    current_batch = np.append(current_batch[:, 1:, :], [[current_pred]], axis=1)

future_predictions_inv = scaler.inverse_transform(future_predictions)

# 2. XỬ LÝ NGÀY THÁNG
# Lấy ngày cuối cùng từ index của file Excel
# (Nếu index của em chưa phải là datetime, mình sẽ lấy ngày hiện tại)
try:
    last_date = pd.to_datetime(df_clean.iloc[:, 0].iloc[-1])
except:
    last_date = pd.Timestamp.now()

# Tạo danh sách 30 ngày làm việc tiếp theo (bỏ qua T7, CN)
future_dates = pd.bdate_range(start=last_date + pd.Timedelta(days=1), periods=30)

# 3. VẼ BIỂU ĐỒ DỰ BÁO TƯƠNG LAI
plt.figure(figsize=(15, 7))
plt.plot(future_dates, future_predictions_inv, marker='o', color='red', label='Giá dự báo 30 ngày tới')

# Định dạng hiển thị ngày tháng trên trục X
plt.gcf().autofmt_xdate()
plt.title(f'DỰ BÁO GIÁ CỔ PHIẾU GOOG TỪ {future_dates[0].strftime("%d/%m/%Y")} ĐẾN {future_dates[-1].strftime("%d/%m/%Y")}')
plt.xlabel('Ngày')
plt.ylabel('Giá dự báo ($)')

# Hiển thị giá trị cụ thể cho một vài điểm tiêu biểu để không bị rối
for i in range(0, 30, 3): # Cứ 3 ngày hiện 1 số cho đẹp
    plt.text(future_dates[i], future_predictions_inv[i], f'{future_predictions_inv[i][0]:.2f}',
             fontsize=9, va='bottom', ha='center', color='darkred')

plt.grid(True, linestyle='--', alpha=0.5)
plt.legend()
plt.show()

# 4. IN RA BẢNG KÈM NGÀY THÁNG
df_result = pd.DataFrame({
    'Ngày': future_dates.strftime('%d/%m/%Y'),
    'Giá Dự Báo': future_predictions_inv.flatten()
})
print("\n--- BẢNG DỰ BÁO CHI TIẾT 30 NGÀY TỚI ---")
print(df_result)