# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q141QR_L2YZbXawAH1WKEDTJE-CEkjOQ
"""

# Mô hình LSTM
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# Đảm bảo cột Date là kiểu datetime và đặt làm Index để hiện ngày tháng trên trục X
# Đọc dữ liệu từ file Excel
data = pd.read_csv('/content/GOOGL_stock.csv', skiprows=3)
data.columns = ['Date','Close','High','Low','Open','Volume']
data['Date'] = pd.to_datetime(data['Date'])
ts = data.set_index('Date')['Close']

# Chuẩn bị dữ liệu cho LSTM
scaler = MinMaxScaler(feature_range=(0, 1))
ts_scaled = scaler.fit_transform(ts.values.reshape(-1, 1))

# Hàm tạo chuỗi dữ liệu cho LSTM
def create_sequences(data, seq_length):
    X, y = [], []
    for i in range(len(data) - seq_length):
        X.append(data[i:i + seq_length])
        y.append(data[i + seq_length])
    return np.array(X), np.array(y)

# Tham số cho LSTM
seq_length = 60 # Độ dài chuỗi (60 ngày)
X, y = create_sequences(ts_scaled, seq_length)

# Chia dữ liệu thành tập huấn luyện và kiểm tra
train_size = int(len(X) * 0.8)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

# Xây dựng mô hình LSTM
lstm_model = Sequential()
lstm_model.add(LSTM(units=50, return_sequences=True, input_shape=(seq_length, 1)))
lstm_model.add(Dropout(0.2))
lstm_model.add(LSTM(units=50, return_sequences=False))
lstm_model.add(Dropout(0.2))
lstm_model.add(Dense(units=1))

# Biên dịch và huấn luyện mô hình
lstm_model.compile(optimizer='adam', loss='mean_squared_error')
lstm_model.fit(X_train, y_train, epochs=20, batch_size=32, verbose=1)

# Dự báo với LSTM
lstm_predictions = lstm_model.predict(X_test)
lstm_predictions = scaler.inverse_transform(lstm_predictions)
y_test_inv = scaler.inverse_transform(y_test)

# Điều chỉnh chỉ số thời gian cho dự báo LSTM
test_dates = ts.index[train_size + seq_length:train_size + seq_length + len(lstm_predictions)]

# 4.3 Dự báo với LSTM
plt.figure(figsize=(12, 6))
plt.plot(ts[:train_size + seq_length], label='Huấn luyện')
plt.plot(test_dates, y_test_inv, label='Thực tế')
plt.plot(test_dates, lstm_predictions, label='Dự báo LSTM', color='green')
plt.title('Dự báo giá đóng cửa GOOG với LSTM')
plt.xlabel('Ngày')
plt.ylabel('Giá đóng cửa')
plt.legend()
plt.show()

# Với LSTM
rmse_lstm = np.sqrt(mean_squared_error(y_test_inv, lstm_predictions))
mae_lstm = mean_absolute_error(y_test_inv, lstm_predictions)
mape_lstm = np.mean(np.abs((y_test_inv - lstm_predictions) / y_test_inv)) * 100
print("\nĐánh giá LSTM:")
print(f'RMSE: {rmse_lstm}')
print(f'MAE: {mae_lstm}')
print(f'MAPE: {mape_lstm}%')

import pickle

# Lưu mô hình LSTM
with open("lstm_model.pkl", "wb") as f:
    pickle.dump(lstm_model, f)

# Lưu scaler
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

from google.colab import files
files.download("lstm_model.pkl")